export const mapCaseStudy = (item: any) => ({
  id: item.id,
  title: item.title,
  slug: item.slug,
  clientName: item.clientName,
  industry: item.industry,
  serviceType: item.serviceType,
  summary: item.summary,
  challenge: item.challenge,
  solution: item.solution,
  outcome: item.outcome,
  results: item.results,
  seoTitle: item.seoTitle,
  seoDescription: item.seoDescription,
  seoKeywords: item.seoKeywords,
  featured: item.featured,
  status: item.status,
  publishedAt: item.publishedAt,
  approvedAt: item.approvedAt,
  submittedForReviewAt: item.submittedForReviewAt,
  archivedAt: item.archivedAt,
  createdAt: item.createdAt,
  updatedAt: item.updatedAt,
});
